name: Data Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  run-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install deps
        run: npm install

      - name: Run data script
        run: node index.js
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          SPORTMONKS_API_KEY: ${{ secrets.SPORTMONKS_API_KEY }}
